[package]
name = "asus/frame-pixelated"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Knit = "sleitnick/knit@1.7.0"
Networker = "leifstout/networker@0.3.0"
Signal = "sleitnick/signal@2.0.3"
TableUtil = "sleitnick/table-util@1.2.1"
EnumList = "sleitnick/enum-list@2.1.0"
Component = "sleitnick/component@2.4.8"
Janitor = "howmanysmall/janitor@1.18.3"
Fusion = "elttob/fusion@0.3.0"
Loader = "sleitnick/loader@1.0.2"
Silo = "sleitnick/silo@0.1.0"
Streamable = "sleitnick/streamable@1.2.3"
Symbol = "sleitnick/symbol@2.0.0"
Timer = "sleitnick/timer@1.1.1"
Sift = "csqrl/sift@0.0.2"
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"
OrderedSet = "hgta1287dev/ordered-set@1.2.0"
BufferUtil = "sleitnick/buffer-util@0.3.2"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"